name: maze2real
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pillow
  - numpy
  - matplotlib
  - pandas
  - stable-baselines3[extra]
  - gymnasium
  - gym
  - dm-env
  - dm-control
  - wandb