name: maze2real
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - cudatoolkit=11.8
  - python=3.12
  - debugpy
  - pillow
  - imageio
  - numpy
  - matplotlib
  - pandas
  - pygame
  - stable-baselines3[extra]
  - ray-rllib
  - gymnasium
  - dm-env
  - dm-control
  - wandb
  pip:
    - gym